[project]
name = "ssm-tools"
version = "0.1.0"
description = "Python toolbox for state-space systems of acoustic systems."
readme = "README.md"
authors = [
    { name = "Art Pelling", email = "a.pelling@tu-berlin.de" }
]
requires-python = ">=3.13"
dependencies = [
    "h5py>=3.14.0",
    "numpy>=2.3.3",
    "scipy>=1.16.2",
    "pyfar@git+https://github.com/pyfar/pyfar.git@8561f4039231cc925f5d2e1dfd8a2eb2719cb28b",
    "numba>=0.62.1",
]

[project.scripts]
ssm-tools = "ssm_tools:main"

[project.optional-dependencies]
across = [
    "across",
]
pymor = [
    "pymor>=2025.1.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ruff>=0.13.0",
]

[tool.basedpyright]
venv = ".venv"
typeCheckingMode = 'off'


[tool.hatch.metadata]
allow-direct-references = true

[tool.uv.sources]
irdl = { workspace = true }
across = { workspace = true }
pyfar = { git = "https://github.com/pyfar/pyfar", rev = "8561f4039231cc925f5d2e1dfd8a2eb2719cb28b" }


[tool.uv.workspace]
members = ["packages/*"]
