[project]
name = "ssm-tools"
version = "0.1.0"
description = "Python toolbox for state-space systems of acoustic systems."
readme = "README.md"
authors = [
    { name = "Art Pelling", email = "a.pelling@tu-berlin.de" }
]
requires-python = ">=3.13"
dependencies = [
    "across",
    "h5py>=3.14.0",
    "irdl",
    "numba>=0.62.1",
    "numpy>=2.3.3",
    "numpydoc>=1.10.0",
    "pyfar@git+https://github.com/pyfar/pyfar.git@state-space-models",
    "pymor>=2025.1.2",
    "scipy>=1.16.2",
    "typer>=0.17.4",
]

[project.scripts]
reduce-fabian = "ssm_tools.scripts.reduce_fabian:main"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ruff>=0.14.8",
]


[tool.hatch.metadata]
allow-direct-references = true


[tool.uv.sources]
across = { workspace = true }
irdl = { workspace = true }
pyfar = { git = "https://github.com/pyfar/pyfar", rev = "1f7f96939447534557a624f012360ce466136b27" }

[tool.uv.workspace]
members = ["packages/*"]


[tool.basedpyright]
venv = ".venv"
typeCheckingMode = 'off'


[tool.ruff]
src = ["src"]
exclude = ["packages/irdl/src/irdl/repositories.py"]
line-length = 120

[tool.ruff.format]
quote-style = "double"

[tool.ruff.lint]
select = ["B", "D", "E", "F", "I", "ICN", "N", "Q", "W"]
ignore = [
    "D100", "D104", "D401",
    "N803",
]

[tool.ruff.lint.pycodestyle]
max-doc-length = 100

[tool.ruff.lint.pydocstyle]
convention = "numpy"
